In [1]:
import requests
from requests.exceptions import ConnectionError
import lxml.html as lh
import pandas as pd
import bs4
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup

In [2]:
companies1 = pd.read_csv('List_of_companies.csv', encoding = "ISO-8859-1") #unmodified names
companies = pd.read_csv('List_of_companies_Full.csv', encoding = "ISO-8859-1") #will have modified names

print(companies.dtypes)

companies['Security'] = companies['Security'].str.replace(u'\xa0', u' ')#this was messing with the classes
companies['Security'] = companies['Security'].str.replace(r' \(Class A\)', '')#some companies are liste multiple times because of class of stock
companies['Security'] = companies['Security'].str.replace(r' \(Class B\)', '')#some companies are liste multiple times because of class of stock
companies['Security'] = companies['Security'].str.replace(r' \(Class C\)', '')#some companies are liste multiple times because of class of stock
companies['Security'] = companies['Security'].str.replace(r'\(', '')#need to remove parenthesis too for the url
companies['Security'] = companies['Security'].str.replace(r'\)', '')
companies['Security'] = companies['Security'].str.replace(r'\.com', '-com')#for amazon and salesforce
companies['Security'] = companies['Security'].str.replace(r'Corporation', 'corp')#corporation got shortened to corp
companies['Security'] = companies['Security'].str.replace(r'corporation', 'corp')
companies['Security'] = companies['Security'].str.replace(r'Company', 'co')#company got shortened to co
companies['Security'] = companies['Security'].str.replace(r'company', 'co')
companies['Security'] = companies['Security'].str.replace(r'&', 'and')#& is and for some reason
companies['Security'] = companies['Security'].str.replace(r' ', '-')#the url uses hyphens a lot
companies['Security'] = companies['Security'].str.replace(r'.', '')#don't want these here
companies['Security'] = companies['Security'].str.replace(r',', '')
companies['Security'] = companies['Security'].str.replace(r'!', '')
companies['Security'] = companies['Security'].str.replace(r'\'', '')

companies['Security'] = companies['Security'].str.lower()#lowercases everything
print(len(companies))
companies

Symbol                   object
Security                 object
SEC filings              object
GICS Sector              object
GICS Sub-Industry        object
Headquarters Location    object
Date first added         object
CIK                       int64
Founded                  object
dtype: object
500

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3m-co,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",8/9/1976,66740,1902
1,ABT,abbott-laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",3/31/1964,1800,1888
2,ABBV,abbvie-inc,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/2012,1551152,2013 (1888)
3,ABMD,abiomed-inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",5/31/2018,815094,1981
4,ACN,accenture-plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/2011,1467373,1989
5,ATVI,activision-blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",8/31/2015,718877,2008
6,ADBE,adobe-inc,reports,Information Technology,Application Software,"San Jose, California",5/5/1997,796343,1982
7,AMD,advanced-micro-devices-inc,reports,Information Technology,Semiconductors,"Santa Clara, California",3/20/2017,2488,1969
8,AAP,advance-auto-parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",7/9/2015,1158449,1932
9,AES,aes-corp-the,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",10/2/1998,874761,1981
10,AFL,aflac-inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",5/28/1999,4977,1955
11,A,agilent-technologies-inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",6/5/2000,1090872,1999
12,APD,air-products-and-chemicals-inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",4/30/1985,2969,1940
13,AKAM,akamai-technologies-inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",7/12/2007,1086222,1998
14,ALK,alaska-air-group-inc,reports,Industrials,Airlines,"Seattle, Washington",5/13/2016,766421,1985
15,ALB,albemarle-corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",7/1/2016,915913,1994
16,ARE,alexandria-real-estate-equities,reports,Real Estate,Office REITs,"Pasadena, California",3/20/2017,1035443,1994
17,ALXN,alexion-pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",5/25/2012,899866,1992
18,ALGN,align-technology,reports,Health Care,Health Care Supplies,"San Jose, California",6/19/2017,1097149,1997
19,ALLE,allegion,reports,Industrials,Building Products,"Dublin, Ireland",12/2/2013,1579241,1908
20,LNT,alliant-energy-corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",7/1/2016,352541,1917
21,ALL,allstate-corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",7/13/1995,899051,1931
22,GOOG,alphabet-inc,reports,Communication Services,Interactive Media & Services,"Mountain View, California",4/3/2006,1652044,1998
23,MO,altria-group-inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",3/4/1957,764180,1985
24,AMZN,amazon-com-inc,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",11/18/2005,1018724,1994
25,AMCR,amcor-plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",6/7/2019,1748790,2019 (1860)
26,AEE,ameren-corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",9/19/1991,1002910,1902
27,AAL,american-airlines-group,reports,Industrials,Airlines,"Fort Worth, Texas",3/23/2015,6201,1934
28,AEP,american-electric-power,reports,Utilities,Electric Utilities,"Columbus, Ohio",3/4/1957,4904,1906
29,AXP,american-express-co,reports,Financials,Consumer Finance,"New York, New York",6/30/1976,4962,1850
...,...,...,...,...,...,...,...,...,...
470,VNO,vornado-realty-trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,1982
471,VMC,vulcan-materials,reports,Materials,Construction Materials,"Birmingham, Alabama",6/30/1999,1396009,1909
472,WRB,berkley-w-r-corp,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",12/5/2019,11544,1967
473,WAB,wabtec-corp,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2/27/2019,943452,1999 (1869)
474,WMT,walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",8/31/1982,104169,1962
475,WBA,walgreens-boots-alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",12/31/1979,1618921,2014
476,DIS,disney-walt-co,reports,Communication Services,Movies & Entertainment,"Burbank, California",6/30/1976,1744489,1923
477,WM,waste-management-inc,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
478,WAT,waters-corp,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
479,WEC,wec-energy-group,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",10/31/2008,783325,1896
480,WFC,wells-fargo-and-company-mn,reports,Financials,Diversified Banks,"San Francisco, California",6/30/1976,72971,1852
481,WELL,welltower-inc,reports,Real Estate,Health Care REITs,"Toledo, Ohio",1/30/2009,766704,1970
482,WST,west-pharmaceutical-svsc-inc,reports,Health Care,Health Care Supplies,"Exton, Pennsylvania",5/22/2020,105770,1923
483,WDC,western-digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","San Jose, California",7/1/2009,106040,1970
484,WU,western-union-co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",9/29/2006,1365135,1851
485,WRK,westrock,reports,Materials,Paper Packaging,"Atlanta, Georgia",NaN,1732845,2015
486,WY,weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,1900
487,WHR,whirlpool-corp,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
488,WMB,williams-cos-inc,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",3/31/1975,107263,1908
489,WLTW,willis-towers-watson,reports,Financials,Insurance Brokers,"London, United Kingdom",1/5/2016,1140536,2016
490,WYNN,wynn-resorts-ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",11/14/2008,1174922,2002
491,XEL,xcel-energy-inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",3/4/1957,72903,1909
492,XRX,xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,1770450,1906
493,XLNX,xilinx,reports,Information Technology,Semiconductors,"San Jose, California",11/8/1999,743988,1984
494,XYL,xylem-inc,reports,Industrials,Industrial Machinery,"White Plains, New York",11/1/2011,1524472,2011
495,YUM,yum-brands-inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",10/6/1997,1041061,1997
496,ZBRA,zebra-technologies-cp-cl-a,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",12/23/2019,877212,1969
497,ZBH,zimmer-biomet-holdings-inc,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",8/7/2001,1136869,1927
498,ZION,zions-bancorporation-na,reports,Financials,Regional Banks,"Salt Lake City, Utah",6/22/2001,109380,1873
499,ZTS,zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",6/21/2013,1555280,1952

In [3]:
#utilities
def getUrl(n, mod = ''):
    currName = companies.at[n, 'Security']
    url='https://www1.salary.com/' + currName + mod + '-Executive-Salaries.html'
    page=requests.get(url)
    return page

def getIncUrl(n):
    currName = companies.at[n, 'Security']
    url='https://www1.salary.com/' + currName + '-inc' + '-Executive-Salaries.html'
    page=requests.get(url)
    return page

def getCoUrl(n):
    currName = companies.at[n, 'Security']
    url='https://www1.salary.com/' + currName + '-co' + '-Executive-Salaries.html'
    page=requests.get(url)
    return page

def getCorpUrl(n):
    currName = companies.at[n, 'Security']
    url='https://www1.salary.com/' + currName + '-corp' + '-Executive-Salaries.html'
    page=requests.get(url)
    return page

def getPlcUrl(n):
    currName = companies.at[n, 'Security']
    url='https://www1.salary.com/' + currName + '-plc' + '-Executive-Salaries.html'
    page=requests.get(url)
    return page

def getContent(page):
    doc=lh.fromstring(page.content)
    tr_elements=doc.xpath('//tr')
    return tr_elements

In [4]:
def failureCase(col, good, alt_tr_elements):
    for j in range(0,len(alt_tr_elements)):
        #T is our j'th row
        T=alt_tr_elements[j]

        #Only check rows of size 4 (with CEO Name, CEO Pay, Median Employee Pay,
        #and CEO Pay Ratio)
        if len(T)==4:
            #checks if the current row has the 4 maagic words
            table_Name = ['','','','']
            i=0
            for t in T:
                name = t.text_content()
                name = name.__str__()
                table_Name[i]=name
                i+=1

            #if it does, I'll take the data from the row right below it
            if (table_Name[0] == 'CEO Name' and table_Name[1] == 'CEO Pay' and table_Name[2] == 'Median Employee Pay' and table_Name[3] == 'CEO Pay Ratio'):
                T=alt_tr_elements[j+1]
                #i is the index of our column
                i=0

                #this is a temporary storage of the content of each line of the csv
                content = []

                #Iterate through each element of the row
                for t in T.iterchildren():
                    #this part if for cleaning the cell contents
                    data=t.text_content() #gets the content of cell
                    data = data.__str__() #turns content to string
                    data = data.replace(r'$', '') #takes out dollar sign for number conversion
                    data = data.replace(r',', '') #takes out comma for number conversion
                    data = data.strip() #clears our \r and \n and spaces, cleans up the content string
                    data = data.replace(r'CEO Pay', '') #cleans up the content string
                    data = data.replace(r'Median Employee Pay', '') #cleans up the content string
                    data = data.replace(r'CEO Pay Ratio', '') #cleans up the content string
                    data = data.replace(r'Ratio', '') #cleans up the content string
                    data = data.replace(r':1', '') #takes out :1 in the ratio for number conversion
                    data = data.strip() #clears our \r and \n and spaces again to finish cleaning up

                    content.append(data)

                    #Check if row is empty
                    if i>0:
                    #Convert any numerical value to integers
                        try:
                            data=int(data)
                        except:
                            pass
                    #Append the data to col
                    col[i + 1][1].append(data)
                    #Increment i for the next column
                    i+=1
                #col[0][1].append(currName1)
                return True

        return False

In [5]:
#Makes a list of to make the graph later on
col=[('Security', [])]

In [ ]:
#goes through all the webpages
for n in range(len(companies)):
    currName = companies.at[n, 'Security']
    add = currName
    #getting url
    url='https://www1.salary.com/' + currName + '-Executive-Salaries.html'
    page=requests.get(url)
    #getting all the tables
    tr_elements=getContent(page)
    #indicates that we failed to find the magics on this particular page
    fail = True
    for j in range(0,len(tr_elements)):
        #T is our j'th row
        T=tr_elements[j]

        #Only check rows of size 4 (with CEO Name, CEO Pay, Median Employee Pay,
        #and CEO Pay Ratio)
        if len(T)==4:
            #checks if the current row has the 4 maagic words
            table_Name = ['','','','']
            i=0
            for t in T:
                name = t.text_content()
                name = name.__str__()
                table_Name[i]=name
                i+=1

            #if it does, I'll take the data from the row right below it
            if (table_Name[0] == 'CEO Name' and table_Name[1] == 'CEO Pay' and table_Name[2] == 'Median Employee Pay' and table_Name[3] == 'CEO Pay Ratio'):
                #print(currName1 + ' good')
                #setting fail to false
                fail = False
                add = currName
                break
    
    if fail:
        #print(currName1)
        #print(currName)
        #print(url)
        #put these into the get url
        alts = ['-inc','-co','-corp','-plc','-new']
        #good indicated whether or not the new url works
        good = False
        for i in range(len(alts)):
            currName = currName + alts[i]
            url='https://www1.salary.com/' + currName + '-Executive-Salaries.html'
            page=requests.get(url)
            alt_tr_elements=getContent(page)
            for j in range(0,len(alt_tr_elements)):
                #T is our j'th row
                T=alt_tr_elements[j]

                #Only check rows of size 4 (with CEO Name, CEO Pay, Median Employee Pay,
                #and CEO Pay Ratio)
                if len(T)==4:
                    #checks if the current row has the 4 maagic words
                    table_Name = ['','','','']
                    i=0
                    for t in T:
                        name = t.text_content()
                        name = name.__str__()
                        table_Name[i]=name
                        i+=1

                    #if it does, I'll take the data from the row right below it
                    if (table_Name[0] == 'CEO Name' and table_Name[1] == 'CEO Pay' and table_Name[2] == 'Median Employee Pay' and table_Name[3] == 'CEO Pay Ratio'):
                        #print(currName1 + ' good')
                        T=alt_tr_elements[j+1]
                        good = True
            if good:
                add = currName
                break
    col[0][1].append(add)
    print(n, add)

0 3m-co
1 abbott-laboratories
2 abbvie-inc
3 abiomed-inc
4 accenture-plc
5 activision-blizzard-inc
6 adobe-inc
7 advanced-micro-devices-inc
8 advance-auto-parts-inc
9 aes-corp-the
10 aflac-inc
11 agilent-technologies-inc
12 air-products-and-chemicals-inc
13 akamai-technologies-inc
14 alaska-air-group-inc
15 albemarle-corp
16 alexandria-real-estate-equities

In [ ]:
col

In [ ]:
len(col[0][1])

In [ ]:
#making the dataframe
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [ ]:
#displaying the dataframe
df

In [ ]:
"""int = 0
for i in range(len(df)):
    if (df.at[i, 'Median Employee Pay'] > -1):
        int += 1
print(int)
print(len(df)-int)"""

int = 0
for i in range(len(df)):
    if (df.at[i, 'Median Employee Pay'] == -1):
        int += 1
        print(i)
        print(df.at[i, 'Company Name'])
int

In [ ]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [ ]:
df

In [ ]:
#verifying correctness

int = 0

for i in range(len(companies)):
    if (df_ratio.at[i, 'GICS Sector'] != companies1.at[i, 'GICS\xa0Sector'] or df_ratio.at[i, 'GICS Sub-Industry'] != companies1.at[i, 'GICS Sub-Industry']):
        int += 1
        print(df.at[i, 'Company Name'] + " is not " + companies1.at[i, 'Security'])
        print(i)
int

In [ ]:
#df.to_csv('quick_names.csv',index=False)

In [ ]:
#df_ratio.to_csv('official_ratio_with_industries.csv',index=False)