In [1]:
import requests
from requests.exceptions import ConnectionError
import lxml.html as lh
import pandas as pd
import bs4
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup

In [2]:
companies = pd.read_csv('List_of_companies.csv', encoding = "ISO-8859-1")

print(companies.dtypes)

companies['Security'] = companies['Security'].str.replace(r' ', '-')
companies['Security'] = companies['Security'].str.replace(r'.', '-')
companies['Security'] = companies['Security'].str.replace(r',', '-')
companies

Symbol                   object
Security                 object
SEC filings              object
GICS Sector              object
GICS Sub-Industry        object
Headquarters Location    object
Date first added         object
CIK                       int64
Founded                  object
dtype: object

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M-Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",8/9/1976,66740,1902
1,ABT,Abbott-Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",3/31/1964,1800,1888
2,ABBV,AbbVie-Inc-,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/2012,1551152,2013 (1888)
3,ABMD,ABIOMED-Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",5/31/2018,815094,1981
4,ACN,Accenture-plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/2011,1467373,1989
5,ATVI,Activision-Blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",8/31/2015,718877,2008
6,ADBE,Adobe-Inc-,reports,Information Technology,Application Software,"San Jose, California",5/5/1997,796343,1982
7,AMD,Advanced-Micro-Devices-Inc,reports,Information Technology,Semiconductors,"Santa Clara, California",3/20/2017,2488,1969
8,AAP,Advance-Auto-Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",7/9/2015,1158449,1932
9,AES,AES-Corp,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",10/2/1998,874761,1981
10,AFL,AFLAC-Inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",5/28/1999,4977,1955
11,A,Agilent-Technologies-Inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",6/5/2000,1090872,1999
12,APD,Air-Products-&-Chemicals-Inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",4/30/1985,2969,1940
13,AKAM,Akamai-Technologies-Inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",7/12/2007,1086222,1998
14,ALK,Alaska-Air-Group-Inc,reports,Industrials,Airlines,"Seattle, Washington",5/13/2016,766421,1985
15,ALB,Albemarle-Corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",7/1/2016,915913,1994
16,ARE,Alexandria-Real-Estate-Equities,reports,Real Estate,Office REITs,"Pasadena, California",3/20/2017,1035443,1994
17,ALXN,Alexion-Pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",5/25/2012,899866,1992
18,ALGN,Align-Technology,reports,Health Care,Health Care Supplies,"San Jose, California",6/19/2017,1097149,1997
19,ALLE,Allegion,reports,Industrials,Building Products,"Dublin, Ireland",12/2/2013,1579241,1908
20,LNT,Alliant-Energy-Corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",7/1/2016,352541,1917
21,ALL,Allstate-Corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",7/13/1995,899051,1931
22,GOOGL,Alphabet-Inc- (Class-A),reports,Communication Services,Interactive Media & Services,"Mountain View, California",4/3/2014,1652044,1998
23,GOOG,Alphabet-Inc- (Class-C),reports,Communication Services,Interactive Media & Services,"Mountain View, California",4/3/2006,1652044,1998
24,MO,Altria-Group-Inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",3/4/1957,764180,1985
25,AMZN,Amazon-com-Inc-,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",11/18/2005,1018724,1994
26,AMCR,Amcor-plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",6/7/2019,1748790,2019 (1860)
27,AEE,Ameren-Corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",9/19/1991,1002910,1902
28,AAL,American-Airlines-Group,reports,Industrials,Airlines,"Fort Worth, Texas",3/23/2015,6201,1934
29,AEP,American-Electric-Power,reports,Utilities,Electric Utilities,"Columbus, Ohio",3/4/1957,4904,1906
...,...,...,...,...,...,...,...,...,...
475,VNO,Vornado-Realty-Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,1982
476,VMC,Vulcan-Materials,reports,Materials,Construction Materials,"Birmingham, Alabama",6/30/1999,1396009,1909
477,WRB,W--R--Berkley-Corporation,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",12/5/2019,11544,1967
478,WAB,Westinghouse-Air-Brake-Technologies-Corp,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2/27/2019,943452,1999 (1869)
479,WMT,Walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",8/31/1982,104169,1962
480,WBA,Walgreens-Boots-Alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",12/31/1979,1618921,2014
481,DIS,The-Walt-Disney-Company,reports,Communication Services,Movies & Entertainment,"Burbank, California",6/30/1976,1744489,1923
482,WM,Waste-Management-Inc-,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
483,WAT,Waters-Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
484,WEC,WEC-Energy-Group,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",10/31/2008,783325,1896
485,WFC,Wells-Fargo,reports,Financials,Diversified Banks,"San Francisco, California",6/30/1976,72971,1852
486,WELL,Welltower-Inc-,reports,Real Estate,Health Care REITs,"Toledo, Ohio",1/30/2009,766704,1970
487,WST,West-Pharmaceutical-Services,reports,Health Care,Health Care Supplies,"Exton, Pennsylvania",5/22/2020,105770,1923
488,WDC,Western-Digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","San Jose, California",7/1/2009,106040,1970
489,WU,Western-Union-Co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",9/29/2006,1365135,1851
490,WRK,WestRock,reports,Materials,Paper Packaging,"Atlanta, Georgia",NaN,1732845,2015
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,1900
492,WHR,Whirlpool-Corp-,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
493,WMB,Williams-Companies,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",3/31/1975,107263,1908
494,WLTW,Willis-Towers-Watson,reports,Financials,Insurance Brokers,"London, United Kingdom",1/5/2016,1140536,2016
495,WYNN,Wynn-Resorts-Ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",11/14/2008,1174922,2002
496,XEL,Xcel-Energy-Inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",3/4/1957,72903,1909
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,1770450,1906
498,XLNX,Xilinx,reports,Information Technology,Semiconductors,"San Jose, California",11/8/1999,743988,1984
499,XYL,Xylem-Inc-,reports,Industrials,Industrial Machinery,"White Plains, New York",11/1/2011,1524472,2011
500,YUM,Yum!-Brands-Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",10/6/1997,1041061,1997
501,ZBRA,Zebra-Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",12/23/2019,877212,1969
502,ZBH,Zimmer-Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",8/7/2001,1136869,1927
503,ZION,Zions-Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",6/22/2001,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",6/21/2013,1555280,1952

In [2]:
#getting url
url='https://www.salary.com/tools/executive-compensation-calculator/walmart-inc-executive-salaries?year=2020'
page=requests.get(url)

#getting all the tables
doc=lh.fromstring(page.content)
tr_elements=doc.xpath('//tr')

In [3]:
#making the csv to write into
filename = "ratio.csv"
f = open(filename, "w")

#writing in the header of the csv
headers = "CEO_Name, CEO_Pay, Median_Employee_Pay, CEO_Pay_Ratio\n"
f.write(headers)

54

In [4]:
#seeing length of each row in the website
[len(T) for T in tr_elements[:]]
#I can probably use this to skip sites that don't have 4 columns

[4, 4, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1]

In [5]:
tcol=[]
i=0

#seeing the content of a specified row this is for testing purposes only
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print(i,name)
    tcol.append((name, []))
tcol

1 CEO Name
2 CEO Pay
3 Median Employee Pay
4 CEO Pay Ratio

[('CEO Name', []),
 ('CEO Pay', []),
 ('Median Employee Pay', []),
 ('CEO Pay Ratio', [])]

In [6]:
#write this into the csv
write_This = ""

#Makes a list of to make the graph later on
col=[('CEO Name', []), ('CEO Pay', []), ('Median Employee Pay', []), ('CEO Pay Ratio', [])]
col

[('CEO Name', []),
 ('CEO Pay', []),
 ('Median Employee Pay', []),
 ('CEO Pay Ratio', [])]

In [7]:
#this will find the table that has the relevant info for the CEO,
#and put the correct info into col
for j in range(0,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]

    #Only check rows of size 4 (with CEO Name, CEO Pay, Median Employee Pay,
    #and CEO Pay Ratio)
    if len(T)==4:
        #checks if the current row has the 4 maagic words
        table_Name = ['','','','']
        i=0
        for t in T:
            name = t.text_content()
            name = name.__str__()
            table_Name[i]=name
            i+=1
        
        #if it does, I'll take the data from the row right below it
        if (table_Name[0] == 'CEO Name' and table_Name[1] == 'CEO Pay' and table_Name[2] == 'Median Employee Pay' and table_Name[3] == 'CEO Pay Ratio'):
            T=tr_elements[j+1]
            #i is the index of our column
            i=0
            
            #this is a temporary storage of the content of each line of the csv
            content = []
            
            #Iterate through each element of the row
            for t in T.iterchildren():
                #this part if for cleaning the cell contents
                data=t.text_content() #gets the content of cell
                data = data.__str__() #turns content to string
                data = data.replace(r'$', '') #takes out dollar sign for number conversion
                data = data.replace(r',', '') #takes out comma for number conversion
                data = data.strip() #clears our \r and \n and spaces, cleans up the content string
                data = data.replace(r'CEO Pay', '') #cleans up the content string
                data = data.replace(r'Median Employee Pay', '') #cleans up the content string
                data = data.replace(r'CEO Pay Ratio', '') #cleans up the content string
                data = data.replace(r'Ratio', '') #cleans up the content string
                data = data.replace(r':1', '') #takes out :1 in the ratio for number conversion
                data = data.strip() #clears our \r and \n and spaces again to finish cleaning up
                
                content.append(data)
                
                #Check if row is empty
                if i>0:
                #Convert any numerical value to integers
                    try:
                        data=int(data)
                    except:
                        pass
                #Append the data to col
                col[i][1].append(data)
                #Increment i for the next column
                i+=1
            write_This = content[0]
            for j in range(1, len(content)):
                write_This += ", " + content[j]
            write_This += "\n"
            f.write(write_This)
            break

In [8]:
write_This

'C. Douglas McMillon, 22105350, 22484, 983\n'

In [9]:
f.close()

In [10]:
#making the dataframe
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [11]:
#displaying the dataframe
df

              CEO Name   CEO Pay  Median Employee Pay  CEO Pay Ratio
0  C. Douglas McMillon  22105350                22484            983